# Generated by Django 2.1.9 on 2019-07-11 11:13

import cbrsservices.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import localflavor.us.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('case_reference', models.CharField(blank=True, max_length=255)),
                ('request_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('cbrs_map_date', models.DateField(blank=True, null=True)),
                ('prohibition_date', models.DateField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('fws_fo_received_date', models.DateField(blank=True, null=True)),
                ('fws_hq_received_date', models.DateField(blank=True, null=True)),
                ('final_letter_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('final_letter_recipient', models.CharField(blank=True, max_length=255)),
                ('analyst_signoff_date', models.DateField(blank=True, null=True)),
                ('qc_reviewer_signoff_date', models.DateField(blank=True, null=True)),
                ('fws_reviewer_signoff_date', models.DateField(blank=True, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=False)),
                ('invalid', models.BooleanField(default=False)),
                ('hard_copy_map_reviewed', models.BooleanField(default=False)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyst', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_case',
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to=cbrsservices.models.CaseFile.casefile_location)),
                ('from_requester', models.BooleanField(default=False)),
                ('final_letter', models.BooleanField(default=False)),
                ('uploaded_date', models.DateField(auto_now_add=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casefiles', to='cbrsservices.Case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casefile_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casefile_modifier', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casefiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_casefile',
            },
        ),
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbrsservices.Case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casetag_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casetag_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_casetag',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('comment', models.TextField()),
                ('acase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cbrsservices.Case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_comment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Determination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('determination', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='determination_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='determination_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_determination',
            },
        ),
        migrations.CreateModel(
            name='FieldOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('field_office_number', models.CharField(max_length=16, unique=True)),
                ('field_office_name', models.CharField(blank=True, max_length=255)),
                ('field_agent_name', models.CharField(blank=True, max_length=255)),
                ('field_agent_email', models.CharField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator])),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldoffice_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldoffice_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_fieldoffice',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaseTag',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.Case')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical case tag',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSystemUnitMap',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical system unit map',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('legal_description', models.CharField(blank=True, max_length=255)),
                ('subdivision', models.CharField(blank=True, max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'db_table': 'cbrs_property',
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('salutation', models.CharField(blank=True, max_length=16)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_requester',
            },
        ),
        migrations.CreateModel(
            name='SystemMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('map_number', models.CharField(max_length=16)),
                ('map_title', models.CharField(blank=True, max_length=255)),
                ('map_date', models.DateField()),
                ('effective', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemmap_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemmap_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_systemmap',
            },
        ),
        migrations.CreateModel(
            name='SystemUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('system_unit_number', models.CharField(max_length=16, unique=True)),
                ('system_unit_name', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunit_creator', to=settings.AUTH_USER_MODEL)),
                ('field_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_units', to='cbrsservices.FieldOffice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunit_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_systemunit',
                'ordering': ['system_unit_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemUnitMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitmap_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitmap_modifier', to=settings.AUTH_USER_MODEL)),
                ('system_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbrsservices.SystemMap')),
                ('system_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbrsservices.SystemUnit')),
            ],
            options={
                'db_table': 'cbrs_systemunitmap',
            },
        ),
        migrations.CreateModel(
            name='SystemUnitProhibitionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('prohibition_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitprohibitiondate_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitprohibitiondate_modifier', to=settings.AUTH_USER_MODEL)),
                ('system_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibition_dates', to='cbrsservices.SystemUnit')),
            ],
            options={
                'db_table': 'cbrs_systemunitprohibitiondate',
                'ordering': ['-prohibition_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('unit_type', models.CharField(max_length=16, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunittype_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunittype_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_systemunittype',
                'ordering': ['unit_type'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbrs_tag',
            },
        ),
        migrations.AddField(
            model_name='systemunit',
            name='system_maps',
            field=models.ManyToManyField(related_name='system_units', through='cbrsservices.SystemUnitMap', to='cbrsservices.SystemMap'),
        ),
        migrations.AddField(
            model_name='systemunit',
            name='system_unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cbrsservices.SystemUnitType'),
        ),
        migrations.AddField(
            model_name='historicalsystemunitmap',
            name='system_map',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.SystemMap'),
        ),
        migrations.AddField(
            model_name='historicalsystemunitmap',
            name='system_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.SystemUnit'),
        ),
        migrations.AddField(
            model_name='historicalcasetag',
            name='tag',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.Tag'),
        ),
        migrations.AddField(
            model_name='casetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbrsservices.Tag'),
        ),
        migrations.AddField(
            model_name='case',
            name='cbrs_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cbrsservices.SystemUnit'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='determination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cbrsservices.Determination'),
        ),
        migrations.AddField(
            model_name='case',
            name='duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cbrsservices.Case'),
        ),
        migrations.AddField(
            model_name='case',
            name='fws_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fws_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='map_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cbrsservices.SystemMap'),
        ),
        migrations.AddField(
            model_name='case',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cbrsservices.Property'),
        ),
        migrations.AddField(
            model_name='case',
            name='qc_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cbrsservices.Requester'),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(related_name='cases', through='cbrsservices.CaseTag', to='cbrsservices.Tag'),
        ),
        migrations.CreateModel(
            name='ReportCase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cbrsservices.case',),
            managers=[
                ('report_case_counts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='systemunitprohibitiondate',
            unique_together={('prohibition_date', 'system_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='systemunitmap',
            unique_together={('system_unit', 'system_map')},
        ),
        migrations.AlterUniqueTogether(
            name='systemmap',
            unique_together={('map_number', 'map_date')},
        ),
        migrations.AlterUniqueTogether(
            name='requester',
            unique_together={('salutation', 'first_name', 'last_name', 'organization', 'email', 'street', 'unit', 'city', 'state', 'zipcode')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('street', 'unit', 'city', 'state', 'zipcode', 'legal_description')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('comment', 'acase')},
        ),
        migrations.AlterUniqueTogether(
            name='casetag',
            unique_together={('case', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='casefile',
            unique_together={('file', 'case')},
        ),
    ]
