# Generated by Django 2.2.9 on 2020-01-21 15:47

import cbrsservices.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('cbrsservices', '0003_auto_20200118_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_reference',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the case reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='distance',
            field=models.FloatField(blank=True, help_text='A numeric value representing the distance the property is from a system unit', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='duplicate',
            field=models.ForeignKey(blank=True, help_text='An integer value that indicates the case number of the original case if this case is a duplicate', null=True, on_delete=django.db.models.deletion.PROTECT, to='cbrsservices.Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='final_letter_recipient',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the full name of the final letter recepient', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='fws_fo_received_date',
            field=models.DateField(blank=True, help_text='The date the field office received the request in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='fws_hq_received_date',
            field=models.DateField(blank=True, help_text='The date the headquarters received the request in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='hard_copy_map_reviewed',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the hard copy of the system map has been reviewed'),
        ),
        migrations.AlterField(
            model_name='case',
            name='invalid',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is invalid'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='on_hold',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is on hold'),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is a priority'),
        ),
        migrations.AlterField(
            model_name='case',
            name='property',
            field=models.ForeignKey(help_text='A foreign key integer value identifying the property this case represents', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cbrsservices.Property'),
        ),
        migrations.AlterField(
            model_name='case',
            name='request_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The date the request for this case was submitted in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(help_text='A comma-separated list of the tags for the given case', related_name='cases', through='cbrsservices.CaseTag', to='cbrsservices.Tag'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casefile_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='file',
            field=models.FileField(help_text='An alphanumeric value of the file path of the uploaded file, which is used to find the file name', upload_to=cbrsservices.models.CaseFile.casefile_location),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='final_letter',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the file is the final letter'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='from_requester',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the file is from the requester'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casefile_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='casetag',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casetag_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casetag',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='casetag',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casetag_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casetag',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='An alphanumeric value of the comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='determination',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='determination_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='determination',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='determination',
            name='description',
            field=models.TextField(blank=True, help_text='An alphanumeric value of a description of the determination'),
        ),
        migrations.AlterField(
            model_name='determination',
            name='determination',
            field=models.CharField(help_text='An alphanumeric value indicating the determination value', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='determination',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='determination_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='determination',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='city',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the city where the field office is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldoffice_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='field_agent_email',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the field office agent's email", max_length=255, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='field_agent_name',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the name of the agent representing the field office', max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='field_office_name',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the name of the field office', max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='field_office_number',
            field=models.CharField(help_text='An alphanumeric value indicating the field office number', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldoffice_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='fieldoffice',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, help_text='An alphanumeric value of the state in which the field office is located', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='case_reference',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the case reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='distance',
            field=models.FloatField(blank=True, help_text='A numeric value representing the distance the property is from a system unit', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='duplicate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='An integer value that indicates the case number of the original case if this case is a duplicate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.Case'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='final_letter_recipient',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the full name of the final letter recepient', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='fws_fo_received_date',
            field=models.DateField(blank=True, help_text='The date the field office received the request in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='fws_hq_received_date',
            field=models.DateField(blank=True, help_text='The date the headquarters received the request in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='hard_copy_map_reviewed',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the hard copy of the system map has been reviewed'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='invalid',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is invalid'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='on_hold',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is on hold'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='priority',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is a priority'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='property',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the property this case represents', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.Property'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='request_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The date the request for this case was submitted in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasefile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcasefile',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasefile',
            name='file',
            field=models.TextField(help_text='An alphanumeric value of the file path of the uploaded file, which is used to find the file name', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcasefile',
            name='final_letter',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the file is the final letter'),
        ),
        migrations.AlterField(
            model_name='historicalcasefile',
            name='from_requester',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the file is from the requester'),
        ),
        migrations.AlterField(
            model_name='historicalcasefile',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcasefile',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetag',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcasetag',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasetag',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcasetag',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='comment',
            field=models.TextField(help_text='An alphanumeric value of the comment'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldetermination',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldetermination',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldetermination',
            name='description',
            field=models.TextField(blank=True, help_text='An alphanumeric value of a description of the determination'),
        ),
        migrations.AlterField(
            model_name='historicaldetermination',
            name='determination',
            field=models.CharField(db_index=True, help_text='An alphanumeric value indicating the determination value', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicaldetermination',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldetermination',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='city',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the city where the field office is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='field_agent_email',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the field office agent's email", max_length=255, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='field_agent_name',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the name of the agent representing the field office', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='field_office_name',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the name of the field office', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='field_office_number',
            field=models.CharField(db_index=True, help_text='An alphanumeric value indicating the field office number', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfieldoffice',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, help_text='An alphanumeric value of the state in which the field office is located', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='city',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the city in which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='legal_description',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the legal description of the property', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='policy_number',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the policy number of the property', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, help_text='An alphanumeric value of the state in which this address is located', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='street',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the street name of this address', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='subdivision',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the subdivision name of the property', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='unit',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the unit at which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, help_text='An alphanumeric value of the zipcode at which this address is located', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='case_reference',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the case reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='distance',
            field=models.FloatField(blank=True, help_text='A numeric value representing the distance the property is from a system unit', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='duplicate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='An integer value that indicates the case number of the original case if this case is a duplicate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.Case'),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='final_letter_recipient',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the full name of the final letter recepient', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='fws_fo_received_date',
            field=models.DateField(blank=True, help_text='The date the field office received the request in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='fws_hq_received_date',
            field=models.DateField(blank=True, help_text='The date the headquarters received the request in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='hard_copy_map_reviewed',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the hard copy of the system map has been reviewed'),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='invalid',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is invalid'),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='on_hold',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is on hold'),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='priority',
            field=models.BooleanField(default=False, help_text='A boolean value (True/False) indicating if the case is a priority'),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='property',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the property this case represents', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.Property'),
        ),
        migrations.AlterField(
            model_name='historicalreportcase',
            name='request_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The date the request for this case was submitted in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='city',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the city in which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='email',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's email", max_length=255, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='first_name',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's first name", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='last_name',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's last name", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='organization',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's organization", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='salutation',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the preferred salutation of the requester', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, help_text='An alphanumeric value of the state in which this address is located', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='street',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the street name of this address', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='unit',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the unit at which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalrequester',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, help_text='An alphanumeric value of the zipcode at which this address is located', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemmap',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemmap',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemmap',
            name='effective',
            field=models.BooleanField(default=True, help_text='A boolean value (True/False) indicating if the map is effective'),
        ),
        migrations.AlterField(
            model_name='historicalsystemmap',
            name='map_number',
            field=models.CharField(help_text='An alphanumeric value of the system map number', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalsystemmap',
            name='map_title',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the title of the system map', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsystemmap',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemmap',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunit',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunit',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunit',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunit',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunit',
            name='system_unit_name',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the system unit name', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsystemunit',
            name='system_unit_number',
            field=models.CharField(db_index=True, help_text='An alphanumeric value of the system unit number', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitmap',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitmap',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitmap',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitmap',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitprohibitiondate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitprohibitiondate',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitprohibitiondate',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitprohibitiondate',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunitprohibitiondate',
            name='system_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the system unit the prohibition was placed on', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cbrsservices.SystemUnit'),
        ),
        migrations.AlterField(
            model_name='historicalsystemunittype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunittype',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunittype',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsystemunittype',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystemunittype',
            name='unit_type',
            field=models.CharField(db_index=True, help_text='An alphanumeric value of the system unit type', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='description',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the tag description'),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='name',
            field=models.CharField(db_index=True, help_text='An alphanumeric value of the tag name', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the city in which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_description',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the legal description of the property', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='policy_number',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the policy number of the property', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, help_text='An alphanumeric value of the state in which this address is located', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the street name of this address', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='subdivision',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the subdivision name of the property', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the unit at which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, help_text='An alphanumeric value of the zipcode at which this address is located', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='city',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the city in which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='requester',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requester',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='email',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's email", max_length=255, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='requester',
            name='first_name',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's first name", max_length=255),
        ),
        migrations.AlterField(
            model_name='requester',
            name='last_name',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's last name", max_length=255),
        ),
        migrations.AlterField(
            model_name='requester',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requester',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='organization',
            field=models.CharField(blank=True, help_text="An alphanumeric value of the requester's organization", max_length=255),
        ),
        migrations.AlterField(
            model_name='requester',
            name='salutation',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the preferred salutation of the requester', max_length=16),
        ),
        migrations.AlterField(
            model_name='requester',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, help_text='An alphanumeric value of the state in which this address is located', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='street',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the street name of this address', max_length=255),
        ),
        migrations.AlterField(
            model_name='requester',
            name='unit',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the unit at which this address is located', max_length=255),
        ),
        migrations.AlterField(
            model_name='requester',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, help_text='An alphanumeric value of the zipcode at which this address is located', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemmap',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemmap_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemmap',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemmap',
            name='effective',
            field=models.BooleanField(default=True, help_text='A boolean value (True/False) indicating if the map is effective'),
        ),
        migrations.AlterField(
            model_name='systemmap',
            name='map_number',
            field=models.CharField(help_text='An alphanumeric value of the system map number', max_length=16),
        ),
        migrations.AlterField(
            model_name='systemmap',
            name='map_title',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the title of the system map', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemmap',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemmap_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemmap',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunit_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunit_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='system_unit_name',
            field=models.CharField(blank=True, help_text='An alphanumeric value of the system unit name', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='system_unit_number',
            field=models.CharField(help_text='An alphanumeric value of the system unit number', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='systemunitmap',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitmap_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunitmap',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunitmap',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitmap_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunitmap',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunitprohibitiondate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitprohibitiondate_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunitprohibitiondate',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunitprohibitiondate',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunitprohibitiondate_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunitprohibitiondate',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunitprohibitiondate',
            name='system_unit',
            field=models.ForeignKey(help_text='A foreign key integer value identifying the system unit the prohibition was placed on', on_delete=django.db.models.deletion.CASCADE, related_name='prohibition_dates', to='cbrsservices.SystemUnit'),
        ),
        migrations.AlterField(
            model_name='systemunittype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunittype_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunittype',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunittype',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemunittype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemunittype',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='systemunittype',
            name='unit_type',
            field=models.CharField(help_text='An alphanumeric value of the system unit type', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the tag description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='modified_date',
            field=models.DateField(auto_now=True, help_text='The date this object was last modified in "YYYY-MM-DD" format', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='An alphanumeric value of the tag name', max_length=255, unique=True),
        ),
    ]
